### PR TITLE
Update the devDependencies for the linter

### PR DESCRIPTION
**Pull request by frankolson**
**What Changed**
- Moved `eslint-config-react-tools` to `devDependencies`
- Add the following to `devDependencies`:
    ```
    eslint-plugin-class-property
    eslint-plugin-jsx-a11y
    ```
- Removed the following from `devDependencies` because they are included in `eslint-config-react-tools`:
    ```
    eslint
    eslint-config-standard
    eslint-plugin-node
    eslint-plugin-standard
    ```

**Related Issues**
- #594

### CODE REVIEW

**Comment by frankolson** [comment]
I can perform the linter errors cleanup after this is merged, or I can do it in this branch as well. The thought didn't really come to me until I submitted this PR.

**Comment by gary-menzel** [comment]
I've just noticed another linting issue (in regard to a forked copy of react-table) since I have enabled the linter (eslint) in the Atom editor. It is complaining that it can't load the 'eslint-plugin-react' module. This is strange because I can see it in the devDependencies.

It may be something I have done but wondered if you use Atom and if you had experienced this.  However, I do have it working perfectly on a separate project.

image

**Comment by frankolson** [comment]
Hmm.. I use Atom and I don't seem to be getting that error, all I am getting are the linter errors caused by the new `eslint` configuration.
screen shot 2017-11-02 at 6 15 42 pm
This might be silly, but maybe you could try deleting your `node_modules/` directory, `yarn` might be caching something weird.

**Comment by gary-menzel** [comment]
I'll take a look - it is not high on my priority list (as I am not doing anything right now directly in the code - I just opened the project to check through the source). It was working fine (it may be an update issue in Atom). I might wait until your PR is applied.

**Comment by gary-menzel** [comment]
@frankolson By chance... do you have eslint (and plugins) installed globally ?

**Comment by gary-menzel** [comment]
@frankolson I must have had my head(s) in the clouds... I had not updated to 6.7.4 in my fork. That is done now and the local updated. I've also merged your eslint peer-dependency changes into my fork.

So - the complaints about not being able to find the modules are gone. There are a stack of eslint messages in Atom (I'm assuming you are getting as well?).

**Comment by frankolson** [comment]
Yah, I assume that it is coming from the the new `eslint` config added in a previous PR. I can fix those errors as well, but I wasn't sure if this community likes configuration changes in different PRs than linter cleanup changes.

**Comment by gary-menzel** [comment]
That is OK - I can live with "real" lint errors coming up (although having trouble getting the Atom linter to actually ignore linting - it decides to complain if linting is disabled in the .eslintignore file. Trying to track that one down now.

I would think that a separate "cosmetic" PR to address all the linter errors would make sense (rather than wrapping it up in a functional PR).  I suspect not everyone is using a real-time linter in Atom (and just relies on running the linter separately - or not at all).

I have noticed that the CI build is failing - that is probably because the lint is failing (it is the only test as far as I can tell).

**Comment by frankolson** [comment]
@tannerlinsley is there something I need to change to get this PR merged?

**Comment by spacedarcy** [comment]
@frankolson Would you mind adding the linter error fixes to this PR as well? I know smaller diffs = better diffs generally, but it would be nice to stop the madness.

**Comment by frankolson** [comment]
@gary-menzel [suggested](https://github.com/react-tools/react-table/pull/596#issuecomment-341859836) that a separate "cosmetic" PR would probably be best after this gets merged in. But I am inclined to just branch off of this branch, fix the errors, and then submit another dependent PR, in hopes that it would push this PR through.

**Comment by gary-menzel** [comment]
@frankolson I'm talking to @tannerlinsley about this. The failing checks will need to get resolved - or (another approach) would be to disable eslint and come back and fixes those breaking lint errors later.

**Comment by frankolson** [comment]
No worries, I can go ahead and resolve those failing checks in this PR

**Comment by frankolson** [comment]
Alright @gary-menzel and @tannerlinsley, the PR has been updated to resolve the failing specs.

**Comment by gary-menzel** [comment]
@tannerlinsley I think this PR should take priority over my most recent one (unless they can both go in at the same time).

**Comment by gary-menzel** [comment]
@frankolson I had some more recent (only a couple of lines and the CHANGELOG update) than your fork so I merged your fork into mine, fixed my changes to match the linter, and that has been committed to master.  I'll just confirm with @tannerlinsley how to process this PR (but the changes should be in now just waiting for a RELEASE).

**Comment by bugzpodder** [comment]
@gary-menzel when is the next release?

**Pull request merged**
