### PR TITLE
Ensure updating columns triggers a re-render

### LINKED ISSUE #662: Updating the columns prop doesn't cause a re-render
## What version of React-Table are you using?
6.6.0

## What bug are you experiencing, or what feature are you proposing?
Updating the columns prop doesn't cause a re-render

## example
https://codesandbox.io/s/2j0kz92y6j

2 buttons have been added to (naively) demonstrate the issue:

Button 1 doesn't work but should, Button 2 forces a re-render by adding an int key prop and incrementing when changing the columns. 

##
suggested fix is to make the componentWillReceiveProps comparison of old columns vs new columns a deep comparison. (I'll create a pull request with a fix shortly).

### PR DESCRIPTION
**Pull request by jontansey**
Add a deep comparison of the columns prop (using `JSON.stringify()`) to the componentWillReceiveProps function.

fixes #662

### CODE REVIEW

**Comment by gary-menzel** [comment]
@tannerlinsley Can you have a look at this one (happy to discuss on Slack).

**Comment by tannerlinsley** [comment]
Please follow this example to see how to update the columns correctly: https://codesandbox.io/s/o4q0lqqwxy

**Comment by jontansey** [comment]
Thanks for your help @tannerlinsley that makes sense.

**Comment by debovis** [comment]
The moral of the above link is use the follow to update columns correctly

`this.setState({
      columns: [...this.state.columns]
 })`

**Pull request closed without merging**
