### PR TITLE
Passes sorting state as props to Th components

### PR DESCRIPTION
**Pull request by simonedavico**
This pull request implements #485, by passing to every column header component its sorting state as a `sorted` prop in the default implementation of `getTheadThProps`. It is easier to render column headers depending on sorting. For example, augmenting the default `ThComponent`:

```javascript
const getIconClass = sorted => {
  if (sorted.desc === undefined) {
    return '';
  } else if (sorted.desc) {
    return '-desc';
  }
  return '-asc';
};

const ColumnHeader = ({ toggleSort, className, children, sorted, ...rest }) => (
  <div
    role='button'
    className={classNames(className, 'rt-th', 'wd-th')}
    onClick={e => {
      if (toggleSort) { toggleSort(e) }
    }}
    {...rest}
  >
    <div
      className={classNames('th-cell', { 'th-sorted': sorted.desc !== undefined })}
    >
      {children}
    </div>
    <div
      className={classNames('th-sort', { 'th-sorted': sorted.desc !== undefined })}
    >
      {
        <Icon
          name={
            `sort${getIconClass(sorted)}`
          }
          size='tiny'
        />
      }
    </div>
  </div>
);
```

The README is updated accordingly.

### CODE REVIEW

**Comment by gary-menzel** [comment]
@simonedavico I've done a review of the approach here and am concerned the changes are modifying the `defaultProps`. If you look at all the other defaults for the `get...Props` they all start as returning an `emptyObj` arrow function (which is basically a `null` function).

The main purpose for these is in writing HOC type extensions so they should remain "clean".

In looking at the code, there is a line in the `makeHeader` function (index.js) that grabs the sort information and then uses that to set the CSS. This same `sort` variable could be added to the `rest` object and would then be passed in as a `prop` to the `ThComponent` (without having to touch the defaultProps). That same `sort` variable could also be passed as a third parameter to the `column.Header` component (so that people could get that information in the `Header` on a specific column without having to override `ThComponent`.

NOTE: To keep it in line with the existing code, the new parameter would be called `sort` (rather than `sorted` - which has been used internally to mean the full set of what is sorted rather than just one parameter of the sort).

The end result would be that `ThComponent` would still get the sort information (as would the `Header`) and the defaultProps would stay "clean".

**Comment by simonedavico** [comment]
Thanks Gary, I'll look into your suggestions and rethink my approach as soon as I can.

**Comment by tannerlinsley** [comment]
Going to close this for now.  Reopen if you want to revisit this :)

**Comment by jadengore** [comment]
@tannerlinsley Willing to rework this if @simonedavico is busy

**Comment by gary-menzel** [comment]
@jadengore Happy to accept solid PRs if you are able to put one together.  The idea is good but just needs to fit the suggestions above to be more aligned with how the code is generally written.

**Pull request closed without merging**
