### PR TITLE
[fix] filter data on all available columns not just visible one

### PR DESCRIPTION
**Pull request by Lolobstant**
> fix for issue : #1111

@tannerlinsley that should do it !

### CODE REVIEW

**Comment by goodmorninggoaway** [comment]
@Lolobstant have you published this fork to npm?

**Comment by tannerlinsley** [comment]
Merged. Will cut a release today sometime.

**Comment by ajha007** [comment]
Please update package as soon as possible.

**Comment by AAraozBAS** [comment]
was implemented this feature? I has 6.10 version and didn't work.

**Comment by courtzc** [comment]
> Merged. Will cut a release today sometime.

@tannerlinsley has this been changed? I'm using the latest version, but I can't filter by "show: false" columns. thanks!

**Pull request merged**
