### PR TITLE
Support for more than 2 levels of headers

### PR DESCRIPTION
**Pull request by mpaupulaire4**
Added support for multiple levels of headers

### CODE REVIEW

**Comment by jharmer-rms** [comment]
This would be really great!

**Comment by tannerlinsley** [comment]
Can we see an example of this?

**Comment by aflansburg** [comment]
Would this allow for usage of a "higher tier" filter? For instance you might have the default text input filter, but above that also have a drop-down filter for specific values.

**Comment by arttay** [comment]
+1ing

**Comment by aflansburg** [comment]
+1ing as well

**Comment by Fornori** [comment]
A feeling that the authors are on vacation; (

**Comment by mpaupulaire-rms** [comment]
@tannerlinsley Would a screen shot suffice?

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.

**Comment by tannerlinsley** [comment]
For realsy's though, this is a huge feature in the next major version. You should see the implementation on a new version branch in github very soon.

**Pull request closed without merging**
